contentProfileConfigList:
- artDecorBaseUrl: https://art-decor.org/decor/services/
  artDecorDocTemplateMap:
    1.2.40.0.34.11.10005: '2014-01-31T00:00:00'
    1.2.40.0.34.11.10006: '2014-01-31T00:00:00'
    1.2.40.0.34.11.10007: '2014-01-31T00:00:00'
    1.2.40.0.34.11.10008: '2014-01-31T00:00:00'
  artDecorMainBaseUrl: https://art-decor.org/decor/services/
  artDecorMainPrefix: elga-
  artDecorProjectMap:
    elga-: https://art-decor.org/decor/services/
    elgabbr-: https://art-decor.org/decor/services/
  targetDir: husky/husky-cda/husky-elga
  targetNamespace: org.husky.cda.elga.generated.artdecor.emed
description: ELGA eMedikation - version of January, 2014
