contentProfileConfigList:
- artDecorBaseUrl: https://art-decor.org/decor/services/
  artDecorDocTemplateMap:
    1.2.40.0.34.11.13: '2016-08-30T16:19:25' 
  artDecorMainBaseUrl: https://art-decor.org/decor/services/
  artDecorMainPrefix: elgaps-
  artDecorProjectMap:
    elgaps-: https://art-decor.org/decor/services/
    elgabbr-: https://art-decor.org/decor/services/
    ad1bbr-: https://art-decor.org/decor/services/ 
    at-cda-bbr-: https://art-decor.org/decor/services/
    ccd1-: https://art-decor.org/decor/services/
  targetDir: husky/husky-cda/husky-elga
  targetNamespace: org.projecthusky.cda.elga.generated.artdecor.ps
description: ELGA Patient Summary - version of August, 2016
