# This code is made available under the terms of the Eclipse Public License v1.0
# in the github project https://github.com/project-husky/husky there you also
# find a list of the contributors and the license information.
#
# This project has been developed further and modified by the joined working group Husky
# on the basis of the eHealth Connector opensource project from June 28, 2021,
# whereas medshare GmbH is the initial and main contributor/author of the eHealth Connector.

contentProfileConfigList:
- artDecorBaseUrl: https://art-decor.org/decor/services/
  artDecorDocTemplateMap:
    2.16.756.5.30.1.1.10.1.3: '2016-05-13T00:00:00'
    2.16.756.5.30.1.1.10.1.4: '2016-05-21T00:00:00'
    2.16.756.5.30.1.1.10.1.13: '2018-01-22T15:17:26'
    2.16.756.5.30.1.1.10.1.5: '2016-05-21T00:00:00'
    2.16.756.5.30.1.1.10.1.6: '2016-05-21T00:00:00'
    2.16.756.5.30.1.1.10.1.7: '2017-04-12T13:57:31'
  artDecorMainBaseUrl: https://art-decor.org/decor/services/
  artDecorMainPrefix: cdachemed-
  artDecorProjectMap:
    IHE-PCC-: https://art-decor.ihe-europe.net/decor/services/
    ch-epr-: https://art-decor.org/decor/services/
    ad2bbr-: https://art-decor.org/decor/services/
    cdachemed-: https://art-decor.org/decor/services/
    ad1bbr-: https://art-decor.org/decor/services/
    ch-pcc-: https://art-decor.org/decor/services/
    ch-pharm-: https://art-decor.org/decor/services/
    hl7chcda-: https://art-decor.org/decor/services/
  targetDir: husky/husky-emed/husky-emed-cda
  targetNamespace: org.husky.emed.cda.generated.artdecor
description: CDA-CH-EMED - Swiss eMedication, draft version 0.97 of February 22, 2021
