# This code is made available under the terms of the Eclipse Public License v1.0
# in the github project https://github.com/project-husky/husky there you also
# find a list of the contributors and the license information.
#
# This project has been developed further and modified by the joined working group Husky
# on the basis of the eHealth Connector opensource project from June 28, 2021,
# whereas medshare GmbH is the initial and main contributor/author of the eHealth Connector.

# The list of all configured value sets that will be used for static and dynamic value set handling in Husky
#
# Required fields for each item in the list are:
#  className:	The fully qualified class name of the enum class that will be generated/overwritten (for static value set handling, only)
#  projectFolder:   	The base folder where the project containing the enum Java class can be found
#  effectiveDate:   	The date and time stamp of the version to download from the CH-EPR repository
#  codeSystemName:  	The code system name that should be set (CODE_SYSTEM_NAME)
#  sourceFormatType: 	JSON, XML or IHESVS
#  sourceSystemType: 	ARTDECOR_FHIR (later also TERMINOLOGIESERVER_SOAP, but this is not implemented, yet)
#  sourceUrl: 	URL where to get the value set in the mentioned sourceFormat from the mentioned sourceSystem
#

description: CDA-CH-EMED ValueSets
status: ACTIVE
valueSetConfigList:
  # DocumentEntry.confidentialityCode and ParticipationFunction is updated by SwissEprValueSetPackageConfig-*.yaml
  - className: org.husky.emed.enums.ActivePharmaceuticalIngredient
    projectFolder: husky-emed/husky-emed-common
    sourceFormatType: JSON
    sourceSystemType: ARTDECOR_FHIR
    sourceUrl: http://art-decor.org/decor/services/RetrieveValueSet?prefix=ch-pharm-&language=en-US&version=&id=2.16.756.5.30.1.1.11.82&format=json
  - className: org.husky.emed.enums.ActSubstanceAdminSubstitutionCode
    projectFolder: husky-emed/husky-emed-common
    sourceFormatType: JSON
    sourceSystemType: ARTDECOR_FHIR
    sourceUrl: http://art-decor.org/decor/services/RetrieveValueSet?prefix=ch-pharm-&language=en-US&version=&id=2.16.756.5.30.1.1.11.81&format=json
  - className: org.husky.emed.enums.ChEmedTimingEvent
    projectFolder: husky-emed/husky-emed-common
    sourceFormatType: JSON
    sourceSystemType: ARTDECOR_FHIR
    sourceUrl: http://art-decor.org/decor/services/RetrieveValueSet?prefix=ch-pharm-&language=en-US&version=&id=2.16.756.5.30.1.127.77.4.11.2&format=json
  - className: org.husky.emed.enums.DispenseSupplyType
    projectFolder: husky-emed/husky-emed-common
    sourceFormatType: JSON
    sourceSystemType: ARTDECOR_FHIR
    sourceUrl: http://art-decor.org/decor/services/RetrieveValueSet?prefix=ch-pharm-&language=en-US&version=&id=2.16.756.5.30.1.127.77.4.11.7&format=json
  - className: org.husky.emed.enums.PharmaceuticalDoseFormEdqm
    projectFolder: husky-emed/husky-emed-common
    sourceFormatType: JSON
    sourceSystemType: ARTDECOR_FHIR
    sourceUrl: http://art-decor.org/decor/services/RetrieveValueSet?prefix=ch-pharm-&language=en-US&version=&id=2.16.756.5.30.1.1.11.3&format=json
  - className: org.husky.emed.enums.RouteOfAdministrationEdqm
    projectFolder: husky-emed/husky-emed-common
    sourceFormatType: JSON
    sourceSystemType: ARTDECOR_FHIR
    sourceUrl: http://art-decor.org/decor/services/RetrieveValueSet?prefix=ch-pharm-&language=en-US&version=&id=2.16.756.5.30.1.1.11.2&format=json
  - className: org.husky.emed.enums.UnitCode
    projectFolder: husky-emed/husky-emed-common
    sourceFormatType: JSON
    sourceSystemType: ARTDECOR_FHIR
    sourceUrl: http://art-decor.org/decor/services/RetrieveValueSet?prefix=ch-pharm-&language=en-US&version=&id=2.16.756.5.30.1.1.11.83&format=json
version:
  label: Current
  validFrom: 2021-04-01T00:00:00+01:00
