contentProfileConfigList:
- artDecorBaseUrl: https://art-decor.org/decor/services/
  artDecorDocTemplateMap:
    2.16.756.5.30.1.1.10.1.15: '2020-06-26T00:00:00'
    2.16.756.5.30.1.1.10.1.16: '2020-06-26T00:00:00'
    2.16.756.5.30.1.1.10.1.17: '2020-06-26T00:00:00'
    2.16.756.5.30.1.1.10.1.18: '2020-06-26T00:00:00'
    2.16.756.5.30.1.1.10.1.19: '2020-06-26T00:00:00'
  artDecorMainBaseUrl: https://art-decor.org/decor/services/
  artDecorMainPrefix: cdachvacd-
  artDecorProjectMap:
    cdachvacd-: https://art-decor.org/decor/services/
    ad2bbr-: https://art-decor.org/decor/services/
    ch-pcc-: https://art-decor.org/decor/services/
    ccd1-: https://art-decor.org/decor/services/
    ad1bbr-: https://art-decor.org/decor/services/
    ch-palm-: https://art-decor.org/decor/services/
    epsos-: https://art-decor.org/decor/services/
    IHE-PCC-: https://art-decor.ihe-europe.net/decor/services/
    hl7chcda-: https://art-decor.org/decor/services/
    ch-epr-: https://art-decor.org/decor/services/
  targetDir: api-java/ehealth_connector-cda/ehealth_connector-cda-ch
  targetNamespace: org.ehealth_connector.cda.ch.vacd.v210
description: CDA-CH-VACD - Swiss eVACDOC, active version 2.1.0 of June 26, 2020
