contentProfileConfigList:
- artDecorBaseUrl: https://art-decor.org/decor/services/
  artDecorDocTemplateMap:
    2.16.756.5.30.1.1.10.1.10: '2020-06-26T00:00:00'
  artDecorMainBaseUrl: https://art-decor.org/decor/services/
  artDecorMainPrefix: cdachlrep-
  artDecorProjectMap:
    ch-epr-: https://art-decor.org/decor/services/
    ch-pcc-: https://art-decor.org/decor/services/
    cdachlrep-: https://art-decor.org/decor/services/
    ch-palm-: https://art-decor.org/decor/services/
    cdachvacd-: https://art-decor.org/decor/services/
    hl7chcda-: https://art-decor.org/decor/services/
  targetDir: api-java/ehealth_connector-cda/ehealth_connector-cda-ch
  targetNamespace: org.ehealth_connector.cda.ch.lrep.v140
description: CDA-CH-LREP - Swiss Laboratory Report - General Report, active version 1.4.0 of June 26, 2020
